// A list of all actions in the system.
import { createTypes } from 'reduxsauce'

export default createTypes(`
	APP_START_ATTEMPT
	APP_START_SUCCESS
	APP_RESET_ATTEMPT
	APP_RESET_SUCCESS
	APP_SET_LOADED_VIDEO
	SET_NOTIFICATION
	RESET_NOTIFICATION

	TOGGLE_DRAWER
	SET_CURRENT_TAB

	GET_NOTIFICATIONS_ATTEMPT
	GET_NOTIFICATIONS_FAILURE
	GET_NOTIFICATIONS_SUCCESS
	PUSHER_NOTIFICATION_RECEIVED

	GET_LOCALE

	REACT_NATIVE_ROUTER_FLUX_REFRESH

	SET_LANGUAGE
	
	LOGIN_ATTEMPT
	LOGIN_SUCCESS
	LOGIN_FAILURE

	SET_REGISTER_INFO
	SEND_PHONE_VERIFICATION_NUMBER_ATTEMPT
	SEND_PHONE_VERIFICATION_NUMBER_SUCCESS
	SEND_PHONE_VERIFICATION_NUMBER_FAILURE

	REGISTER_ATTEMPT
	REGISTER_SUCCESS
	REGISTER_FAILURE
	SIGNOUT

	FORGOT_PASSWORD_ATTEMPT
	FORGOT_PASSWORD_SUCCESS
	FORGOT_PASSWORD_FAILURE

	RESET_PASSWORD_ATTEMPT
	RESET_PASSWORD_SUCCESS
	RESET_PASSWORD_FAILURE
	
	GET_CITIES_ATTEMPT
	GET_CITIES_SUCCESS
	GET_CITIES_FAILURE

	GET_VOICE_MESSAGES_ATTEMPT
	GET_VOICE_MESSAGES_SUCCESS
	GET_VOICE_MESSAGES_FAILURE

	GET_MESSAGES_ATTEMPT
	GET_MESSAGES_SUCCESS
	GET_MESSAGES_FAILURE

	SEND_MESSAGES_ATTEMPT
	SEND_MESSAGES_SUCCESS
	SEND_MESSAGES_FAILURE,

`)
